### ISSUE TITLE
Add foreign regions suppressed

### ISSUE THREAD

**Issue by nicholasricci** [devnix/belfiore-code#6]
It is possible to add foreign regions suppressed to the list? I think that is a good idea to have them with property active/discontinued like cities, it is worth to check Italian tax code for foreign people.

**Comment by devnix** [comment]
Hi @nicholasricci! If I'm not mistaken, the information you need is not available in the official data source: https://www.istat.it/it/files/2011/01/Elenco-codici-e-denominazioni-unita-territoriali-estere.zip

**Comment by nicholasricci** [comment]
Hi @devnix, this is the official data source:
https://www.istat.it/it/files//2011/01/Elenco-Paesi-esteri-cessati.zip

**Comment by devnix** [comment]
So, we should have to cross multiple data sources. Right now I don't have the time to check it out but I gladly accept a PR :)
